[package]
name = "riscvm-core"
version = "0.1.0"
edition = "2021"

[dependencies]
bit = "0.1.1"
elf = "0.7.4"
goblin = "0.9.2"
intervaltree = "0.2.7"
linux-libc-auxv = { git = "https://github.com/mateocabanal/linux-libc-auxv" }
rand = "0.8.5"
thiserror = "2"
tracing = "0.1.40"
